# ------------------------------------------------------------------------------ #
# 基础设置 https://www.home-assistant.io/docs/configuration/basic/
# ------------------------------------------------------------------------------ #
homeassistant:
  # 系统的名字
  name: Home
  # 纬度和经度，计算太阳升起和设定时间所需位置，越精确越好
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  # 海拔高度用于修正天气参数和日出日落时间参数 (默认单位是：米)
  elevation: !secret homeassistant_elevation
  # 度量衡单位制式（metric）是公制，（imperial）是英制
  unit_system: metric
  # 时区，可以从这里查找: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Shanghai
  # 用于一些个性化的设置 https://www.home-assistant.io/docs/configuration/customizing-devices/
  customize: !include customize.yaml
  customize_domain: !include customize_domain.yaml
  customize_glob: !include customize_glob.yaml
  # 登陆验证 https://www.home-assistant.io/docs/authentication/providers/
  auth_providers:
   - type: homeassistant
#   - type: legacy_api_password
   - type: trusted_networks
     trusted_networks:
      - 127.0.0.1
#      - ::1
      - 192.168.0.0/24
#      - fd00::/8
    
# ------------------------------------------------------------------------------ #
# 某些配置暂时不需要的话，请在前面加上#号
# 对配置不明白的可以去看官方的介绍
# ------------------------------------------------------------------------------ #

# ------------------------------------------------------------------------------ #
# 显示系统运行状态 https://www.home-assistant.io/components/system_health
# ------------------------------------------------------------------------------ #
system_health:

# ------------------------------------------------------------------------------ #
# 在首页显示简介 https://www.home-assistant.io/components/introduction
# ------------------------------------------------------------------------------ #
introduction:

# ------------------------------------------------------------------------------ #
# 前端显示设置 https://www.home-assistant.io/components/frontend/
# ------------------------------------------------------------------------------ #
frontend:
#  javascript_version: latest
  themes: !include themes.yaml

# ------------------------------------------------------------------------------ #
# 侧边栏 https://www.home-assistant.io/components/panel_iframe/
# ------------------------------------------------------------------------------ #
panel_iframe:
  hassbian:
    title: 瀚思彼岸论坛
    icon: mdi:wrench
    url: https://bbs.hassbian.com


# ------------------------------------------------------------------------------ #
# lovelace界面 https://www.home-assistant.io/lovelace
# 下方设置需要配合 ui-lovelace.yaml 使用，进行lovelace相关配置
# ------------------------------------------------------------------------------ #
#lovelace:
#  mode: yaml

# ------------------------------------------------------------------------------ #
# 在侧边栏显示配置菜单 https://www.home-assistant.io/components/config/
# ------------------------------------------------------------------------------ #
config:

# ------------------------------------------------------------------------------ #
# 云 相关 https://www.home-assistant.io/components/cloud/
# ------------------------------------------------------------------------------ #
cloud:

# ------------------------------------------------------------------------------ #
# 手机APP调用API https://www.home-assistant.io/components/mobile_app/
# ------------------------------------------------------------------------------ #
#mobile_app:

# ------------------------------------------------------------------------------ #
# 用户相关(设备追踪等) https://www.home-assistant.io/components/person/
# ------------------------------------------------------------------------------ #
person:

# ------------------------------------------------------------------------------ #
# 分组 https://www.home-assistant.io/components/group/
# ------------------------------------------------------------------------------ #
#group: !include_dir_merge_named group
group: !include groups.yaml

# ------------------------------------------------------------------------------ #
# 自动化 https://www.home-assistant.io/components/automation/
# ------------------------------------------------------------------------------ #
automation: !include automations.yaml

# ------------------------------------------------------------------------------ #
# 脚本 https://www.home-assistant.io/components/script/
# ------------------------------------------------------------------------------ #
script: !include scripts.yaml

# ------------------------------------------------------------------------------ #
# 命令行 https://www.home-assistant.io/components/shell_command/
# ------------------------------------------------------------------------------ #
shell_command: !include shell_command.yaml

# ------------------------------------------------------------------------------ #
# Apple HomeKit https://www.home-assistant.io/components/homekit
# ------------------------------------------------------------------------------ #
#homekit:

# ------------------------------------------------------------------------------ #
# Custom Updater自制插件、JS升级辅助工具 
# 来源： https://github.com/custom-components/custom_updater
# ------------------------------------------------------------------------------ #
custom_updater:
#  hide_sensor: true
#  show_installable: false
#  track:
#    - components
#    - cards
#    - python_scripts
#  card_urls:
#    - 
#  component_urls:
#    - 
#  python_script_urls:
#    -

# ------------------------------------------------------------------------------ #
# mqtt相关配置 https://www.home-assistant.io/components/mqtt/
# ------------------------------------------------------------------------------ #
mqtt:
  password: !secret mqtt_password

  
# ------------------------------------------------------------------------------ #
# 网络相关配置 https://www.home-assistant.io/components/http/
# ------------------------------------------------------------------------------ #
http:
  api_password: !secret api_password
  # 默认只接受IPv4访问，如果要使用IPv6访问，取消注释，二者只能选一种
#  server_host: ::0
#  server_port: 8123
  # 外网地址，配合iOS app使用效果更佳
#  base_url: !secret base_url
#  ssl_certificate: /config/ssl/XXX.pem
#  ssl_key: /config/ssl/XXX.key
  # 跨站点请求
#  cors_allowed_origins:
#    - https://google.com
#    - https://www.home-assistant.io
  # 启用XFF请求头，配合代理配置使用，默认False
#  use_x_forwarded_for: true
  # 信任的代理
#  trusted_proxies:
#    - 127.0.0.1
#    - ::1
  # 信任的网络
#  trusted_networks:
#    - 127.0.0.1
#    - ::1
#    - 192.168.0.0/24
#    - fd00::/48
  # 启用账密穷举保护机制
  ip_ban_enabled: true
  # 输错密码次数
  login_attempts_threshold: 5

# ------------------------------------------------------------------------------ #
# 检查更新 https://www.home-assistant.io/components/updater/
# ------------------------------------------------------------------------------ #
updater:
  # 包含已使用的插件
  include_used_components: true

# ------------------------------------------------------------------------------ #
# 系统自动发现设备 https://www.home-assistant.io/components/discovery/
# ------------------------------------------------------------------------------ #
#discovery:
#  ignore:
#    - samsung_tv

# ------------------------------------------------------------------------------ #
# 使用浏览器的语音命令 https://www.home-assistant.io/components/conversation/
# ------------------------------------------------------------------------------ #
#conversation:

# ------------------------------------------------------------------------------ #
# 数据记录 https://www.home-assistant.io/components/recorder/
# 默认存储位置 home-assistant_v2.db
# ------------------------------------------------------------------------------ #
recorder: !include recorder.yaml

# ------------------------------------------------------------------------------ #
# 在侧边栏显示历史菜单 https://www.home-assistant.io/components/history/
# 依赖recorder 设置，history中设置的必须在recorder内有，不然没有数据显示
# ------------------------------------------------------------------------------ #
history: !include history.yaml

# ------------------------------------------------------------------------------ #
# 控制台打印的日志信息 https://www.home-assistant.io/components/logger/
# 也会保存在 home-assistant.log
# ------------------------------------------------------------------------------ #
logger: !include logger.yaml

# ------------------------------------------------------------------------------ #
# 在侧边栏显示日志菜单 https://www.home-assistant.io/components/logbook/
# ------------------------------------------------------------------------------ #
logbook: !include logbook.yaml

# ------------------------------------------------------------------------------ #
# 地图 https://www.home-assistant.io/components/map/
# ------------------------------------------------------------------------------ #
#map:

# ------------------------------------------------------------------------------ #
# 日出日落 https://www.home-assistant.io/components/sun/
# ------------------------------------------------------------------------------ #
sun:

# ------------------------------------------------------------------------------ #
# 文字转语音 https://www.home-assistant.io/components/tts/
# ------------------------------------------------------------------------------ #
#tts:
#  - platform: baidu
    # https://cloud.baidu.com/product/speech/tts
#    app_id: YOUR_APPID
#    api_key: YOUR_APIKEY
#    secret_key: YOUR_SECRETKEY
    # 语速 默认5，可选0--9
#    speed: 5
    # 音调 默认5，可选0--9
#    pitch: 6
    # 音量 默认5，可选0--15
#    volume: 
    # 人格 默认0，可选0, 1, 3, 4
#    person: 2

# ------------------------------------------------------------------------------ #
# 传感器 https://www.home-assistant.io/components/sensor/
# ------------------------------------------------------------------------------ #
sensor:
  - platform: systemmonitor
    resources:
      - type: memory_use_percent
      - type: processor_use
      - type: last_boot

# ------------------------------------------------------------------------------ #
# modbus https://www.home-assistant.io/components/modbus/
# ------------------------------------------------------------------------------ #
#modbus:
#  type: rtuovertcp
#  host: 192.168.10.101
#  port: 8899

# ------------------------------------------------------------------------------ #
# 温控器 https://www.home-assistant.io/components/climate/
# ------------------------------------------------------------------------------ #
#climate:
#  - platform: demo

# ------------------------------------------------------------------------------ #
# 卷帘（窗帘、卷门等）https://www.home-assistant.io/components/cover/
# ------------------------------------------------------------------------------ #
#cover:
#  - platform: demo

# ------------------------------------------------------------------------------ #
# 电扇 https://www.home-assistant.io/components/fan/
# ------------------------------------------------------------------------------ #
#fan:
#  - platform: demo

# ------------------------------------------------------------------------------ #
# 摄像头 https://www.home-assistant.io/components/camera/
# ------------------------------------------------------------------------------ #
#camera:
#  - platform: demo

# ------------------------------------------------------------------------------ #
# 灯 https://www.home-assistant.io/components/light/
# ------------------------------------------------------------------------------ #
#light:
#  - platform: demo
  
# ------------------------------------------------------------------------------ #
# 锁 https://www.home-assistant.io/components/lock/
# ------------------------------------------------------------------------------ #
#lock:
#  - platform: demo

# ------------------------------------------------------------------------------ #
# 媒体播放器 https://www.home-assistant.io/components/media_player/
# ------------------------------------------------------------------------------ #
#media_player:
#  - platform: demo

# ------------------------------------------------------------------------------ #
# 遥控器 https://www.home-assistant.io/components/remote/
# ------------------------------------------------------------------------------ #
#remote:
#  - platform: demo

# ------------------------------------------------------------------------------ #
# 开关 https://www.home-assistant.io/components/switch/
# ------------------------------------------------------------------------------ #
#switch:
#  - platform: demo

# ------------------------------------------------------------------------------ #
# 天气 https://www.home-assistant.io/components/weather/
# ------------------------------------------------------------------------------ #
#weather:
#  - platform: demo

# ------------------------------------------------------------------------------ #
# 空气质量 https://www.home-assistant.io/components/air_quality/
# ------------------------------------------------------------------------------ #
#air_quality:
#  - platform: demo

# ------------------------------------------------------------------------------ #
# 报警控制面板 https://www.home-assistant.io/components/alarm_control_panel/
# ------------------------------------------------------------------------------ #
#alarm_control_panel:
#  - platform: demo

# ------------------------------------------------------------------------------ #
# 二进制传感器 https://www.home-assistant.io/components/binary_sensor/
# ------------------------------------------------------------------------------ #
#binary_sensor:
#  - platform: demo

# ------------------------------------------------------------------------------ #
# 地理位置信息 https://www.home-assistant.io/components/geo_location/
# ------------------------------------------------------------------------------ #
#geo_location:
#  - platform: demo

# ------------------------------------------------------------------------------ #
# 图像处理 https://www.home-assistant.io/components/image_processing/
# ------------------------------------------------------------------------------ #
#image_processing:
#  - platform: demo

# ------------------------------------------------------------------------------ #
# 通知 https://www.home-assistant.io/components/notify/
# ------------------------------------------------------------------------------ #
#notify:
#  - platform: demo



