# ------------------------------------------------------------------------------ #
# 数据记录 https://www.home-assistant.io/components/recorder/
# 默认存储位置 home-assistant_v2.db
# ------------------------------------------------------------------------------ #

#db_url: sqlite:///data/home-assistant_v2.db
#purge_interval: 1
#purge_keep_days: 30
#include:
#  entities:
#    - group.landscaping
#exclude:
#  domains:
#    - updater
#    - automation
#    - device_tracker
#    - group
#    - scene
#    - script
#  entities:
#    - sensor.ha_uptime