# ------------------------------------------------------------------------------
# 保存密码等敏感信息 https://home-assistant.io/docs/configuration/secrets/
# ------------------------------------------------------------------------------
# 地理位置信息
homeassistant_latitude: 40
homeassistant_longitude: 130
homeassistant_elevation: 3
# api密码
api_password: ushw3sjw3sb728h&2$6h*n@382q)jdbw*&%hdg
# MQTT密码
mqtt_password: pass_mqtt
